### ISSUE TITLE
Are you sure this is a "Serializer"?

### ISSUE THREAD

**Issue by char-ptr** [NotDSF/leopard#1]
Based on what you've shown uhm im kinda confused why you named it lua serializer when i don't see how it serializes it? seralization is the act of converting some data type or object into something else, for example converting a javascript object into json would be seralization, or more conventional use cases are converting a struct into bytes which can be deserialized later; basically for saving the state of the object.

**Comment by pozm** [comment]
Just so you know - a lua serializer would convert lua code (or functions etc) into bytecode, so something like luac.

**Comment by NotDSF** [comment]
This turns objects into strings

**Comment by NotDSF** [comment]
due to obvious limitations, I cannot reconstruct a lua function (which is what you were talking about to me on tg), I can only create a function definition using the `debug.getinfo` function which provides the functions params, isvararg, and name. However what I could do is search the environment for that function and return the index, however that would be inefficient.

**Comment by NotDSF** [comment]
and in term of deserialization just simply use `loadstring("return" .. Output)()`
example:
```lua
local Serialize = loadstring(game:HttpGet("https://raw.githubusercontent.com/NotDSF/Lua-Serializer/main/Serializer.lua"))();
local Output = Serialize({ 1, 2, true, "Hello World", function() end });
local Table = loadstring("return" .. Output)();

print(Table[4]); --> Hello World
```

**Comment by pozm** [comment]
you do not understand seralization.

**Comment by NotDSF** [comment]
https://github.com/Rochet2/LuaSerializer/
https://github.com/pkulchenko/serpent
https://github.com/bakpakin/binser

**Comment by pozm** [comment]
what they do is completely different from yours.

**Comment by pozm** [comment]
Please stop beign so arrogant and accept that what you have made is a pretty printer / formatter and NOT a serializer. honestly it's just embarrassing at this point.

**Comment by NotDSF** [comment]
> what they do is completely different from yours.

How so?
